services:
 listener-ne:
   build: .
   container_name: ais-listener-ne
   restart: unless-stopped
   environment:
     - PYTHONUNBUFFERED=1
     - OVH_REGION=gra
     - OVH_ACCESS_KEY=${OVH_ACCESS_KEY}
     - OVH_SECRET_KEY=${OVH_SECRET_KEY}
     - AISSTREAM_TOKEN=${AISSTREAM_TOKEN}
   command: ["--id", "listener_ne", "--shard", "NE"]
   logging:
     driver: "json-file"
     options:
       max-size: "10m"
       max-file: "3"
